FROM python:3.11

WORKDIR /app/smart_warehouse_ai

COPY smart_warehouse_ai/ ./

COPY smart_warehouse_ai/requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8001

CMD ["uvicorn", "ai_service:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]