FROM python:3.11-slim

WORKDIR /app

RUN mkdir -p /root/.cache/pip

COPY smart_warehouse_ai/v1.2/requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt

ENV PATH="/root/.local/bin:$PATH"

COPY smart_warehouse_ai/v1.2/ .

EXPOSE 8001

CMD ["sh", "-c", "python -m scripts.train_local && uvicorn app.main:app --host 0.0.0.0 --port 8001"]