FROM python:3.11

WORKDIR /app/smart_warehouse_ai/v1.2

COPY smart_warehouse_ai/v1.2 ./

COPY smart_warehouse_ai/v1.2/requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8001

CMD ["sh", "-c", "python -m scripts.train_local && uvicorn app.main:app --host 0.0.0.0 --port 8001"]
