spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.highlight_sql: true

springdoc:
  swagger-ui:
    persistAuthorization: true
    tryItOutEnabled: true
    displayRequestDuration: true
    docExpansion: none

security:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    ru.rtc.warehouse: debug
    org.springframework.web: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace