spring:
  application:
    name: warehouse
  profiles:
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    lettuce:
      pool:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/master-changelog-v1.2.5.yaml
    enabled: true
    clear-checksums: true

server:
  port: ${APP_PORT:8080}

security:
  jwt:
    access-token-exp-seconds: 86400000
    refresh-token-exp-seconds: 1209600

app:
  dashboard:
    push-interval-ms: 30000
    ttl:
      minute-series-seconds: 4000
      checked-day-days: 3

warehouse:
  robot:
    recent-scans-key-template: "robot:%s:recent_scans"
    redis-channel: "ws:robot_updates"
    ws-global-topic: "/topic/dashboard"
    ws-robot-topic-prefix: "/topic/dashboard/robot"
    ws-warehouse-topic-prefix: "/topic/dashboard/warehouse"
    ws-global-locations-topic: "/topic/dashboard/locations"
    ws-warehouse-locations-topic-prefix: "/topic/dashboard/warehouse"
    recent-scans-limit: 5
    heartbeat-millis: 5000
    recent-scans-ttl-days: 7
  location:
    heartbeat-millis: 600000
    recent-threshold-minutes: 15
    medium-threshold-minutes: 120
