databaseChangeLog:
  - changeSet:
      id: v1.1-create-products
      author: dev
      preConditions:
        - not:
            tableExists:
              tableName: products
      changes:
        - createTable:
            tableName: products
            remarks: Товары
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: warehouse_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_product_warehouse
                    references: warehouses(id)
              - column:
                  name: sku_code
                  type: VARCHAR(50)
                  constraints:
                    unique: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: category
                  type: VARCHAR(100)
              - column:
                  name: min_stock
                  type: INTEGER
                  defaultValueNumeric: 10
              - column:
                  name: optimal_stock
                  type: INTEGER
                  defaultValueNumeric: 100
              - column:
                  name: is_deleted
                  type: BOOLEAN
                  defaultValueBoolean: false
